import { EmployerSchema } from '../schema';

export const employers: EmployerSchema[] = [
  {
    id: '1',
    fullname: 'Carlin Camacho',
    gender: 'Male',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 1,
    phoneNumber: '780-371-5012',
    phoneNumberStatus: false,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: true,
    image: 'https://img.png',
  },
  {
    id: '2',
    fullname: 'Joly Borland',
    gender: 'Female',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 2,
    phoneNumber: '216-367-3820',
    phoneNumberStatus: false,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: true,
    image: 'https://img.png',
  },
  {
    id: '3',
    fullname: 'Vivian Duffield',
    gender: 'Female',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 3,
    phoneNumber: '369-475-3875',
    phoneNumberStatus: false,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: false,
    image: 'https://img.png',
  },
  {
    id: '4',
    fullname: 'Kaylil Mohan',
    gender: 'Female',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 4,
    phoneNumber: '493-409-8452',
    phoneNumberStatus: true,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: true,
    image: 'https://img.png',
  },
  {
    id: '5',
    fullname: 'Joe Tyrer',
    gender: 'Male',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 5,
    phoneNumber: '105-221-0238',
    phoneNumberStatus: true,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: true,
    image: 'https://img.png',
  },
  {
    id: '6',
    fullname: 'Geno Rikkard',
    gender: 'Male',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 6,
    phoneNumber: '159-544-1139',
    phoneNumberStatus: false,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: false,
    image: 'https://img.png',
  },
  {
    id: '7',
    fullname: 'Charlena Gritton',
    gender: 'Female',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 7,
    phoneNumber: '493-201-7294',
    phoneNumberStatus: true,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: true,
    image: 'https://img.png',
  },
  {
    id: '8',
    fullname: 'Wilhelmina Sitlington',
    gender: 'Female',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 8,
    phoneNumber: '173-550-2302',
    phoneNumberStatus: true,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: true,
    image: 'https://img.png',
  },
  {
    id: '9',
    fullname: 'Larina Dewicke',
    gender: 'Female',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 9,
    phoneNumber: '644-632-4850',
    phoneNumberStatus: false,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: false,
    image: 'https://img.png',
  },
  {
    id: '10',
    fullname: 'Ardella Bonnier',
    gender: 'Female',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 10,
    phoneNumber: '606-300-8902',
    phoneNumberStatus: false,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: false,
    image: 'https://img.png',
  },
  {
    id: '11',
    fullname: 'Beltran Hallward',
    gender: 'Male',
    positionId: 21,
    skype: 'https://www.skype.com/en/features/skype-web/',
    companyId: 11,
    phoneNumber: '345-371-2126',
    phoneNumberStatus: true,
    license:
      'https://file.thanhtravietnam.vn/data/0/images/2023/09/18/upload_2143/giay-chung-nhan-ho-kinh-doanh.jpg?dpi=150&quality=100&w=780',
    licenseStatus: true,
    image: 'https://img.png',
  },
];
