import { PositionSchema } from '../schema';

export const positions: PositionSchema[] = [
  { id: 1, name: 'General Manager' },
  { id: 2, name: 'Media Manager IV' },
  { id: 3, name: 'Health Coach I' },
  { id: 4, name: 'Design Engineer' },
  { id: 5, name: 'Accounting Assistant I' },
  { id: 6, name: 'Financial Analyst' },
  { id: 7, name: 'Graphic Designer' },
  { id: 8, name: 'Budget/Accounting Analyst IV' },
  { id: 9, name: 'Research Associate' },
  { id: 10, name: 'Software Engineer I' },
  { id: 11, name: 'Mechanical Systems Engineer' },
  { id: 12, name: 'Food Chemist' },
  { id: 13, name: 'Executive Secretary' },
  { id: 14, name: 'Assistant Professor' },
  { id: 15, name: 'Administrative Officer' },
  { id: 16, name: 'Internal Auditor' },
  { id: 17, name: 'Technical Writer' },
  { id: 18, name: 'Actuary' },
  { id: 19, name: 'Chief Design Engineer' },
  { id: 20, name: 'Marketing Specialist' },
  { id: 21, name: 'HR Manager' },
  { id: 22, name: 'Project Manager' },
  { id: 23, name: 'Sales Representative' },
  { id: 24, name: 'Customer Service Representative' },
  { id: 25, name: 'Operations Manager' },
  { id: 26, name: 'Quality Assurance Analyst' },
  { id: 27, name: 'Web Developer' },
  { id: 28, name: 'Data Analyst' },
  { id: 29, name: 'Network Engineer' },
  { id: 30, name: 'Product Manager' },
  { id: 31, name: 'UX Designer' },
  { id: 32, name: 'UI Developer' },
  { id: 33, name: 'Security Analyst' },
  { id: 34, name: 'Supply Chain Manager' },
  { id: 35, name: 'Logistics Coordinator' },
  { id: 36, name: 'Operations Coordinator' },
  { id: 37, name: 'Event Coordinator' },
  { id: 38, name: 'Public Relations Specialist' },
  { id: 39, name: 'Content Writer' },
  { id: 40, name: 'Human Resources Coordinator' },
  { id: 41, name: 'Recruiter' },
  { id: 42, name: 'Financial Controller' },
  { id: 43, name: 'Legal Counsel' },
  { id: 44, name: 'Business Development Manager' },
  { id: 45, name: 'Account Manager' },
  { id: 46, name: 'Brand Manager' },
  { id: 47, name: 'Market Research Analyst' },
  { id: 48, name: 'Social Media Manager' },
  { id: 49, name: 'Operations Analyst' },
  { id: 50, name: 'IT Manager' },
];
