// import { Application } from '../entities/application.entity';
// import { NotificationStatus } from '../../domain/aggregate';
import { CvSchema } from '../schema';

export const cvs: CvSchema[] = [
  {
    id: 1,
    templateId: 1,
    link: 'https://www.myperfectresume.com/wp-content/uploads/2023/05/teacher-resume-example.svg',
    createdAt: '28-01-24',
    isPublic: false,
    lastModified: '25-04-23',
    userId: 15,
  },
  {
    id: 2,
    templateId: 1,
    link: 'https://www.myperfectcv.co.uk/cv/examples',
    createdAt: '15-04-24',
    isPublic: true,
    lastModified: '02-12-23',
    userId: 16,
  },
  {
    id: 3,
    templateId: 1,
    link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-mOgTw8nl70CAcrRZ9NWYqfA9J3BuG8epy_7QpnapMw&s',
    createdAt: '25-05-23',
    isPublic: false,
    lastModified: '29-01-24',
    userId: 17,
  },
  {
    id: 4,
    templateId: 1,
    link: 'https://enhancv.com/localized/_next/static/images/resumeImg-5a6274872a0055ccc1d1f27ea1e0b347.webp',
    createdAt: '26-05-23',
    isPublic: true,
    lastModified: '30-12-23',
    userId: 18,
  },
  {
    id: 5,
    templateId: 1,
    link: 'https://www.hloom.com/images/marketing-intern-cv-template-standout.svg',
    createdAt: '09-08-23',
    isPublic: false,
    lastModified: '04-05-23',
    userId: 19,
  },
  {
    id: 6,
    templateId: 1,
    link: 'https://www.hloom.com/images/marketing-intern-cv-template-standout.svg',
    createdAt: '25-05-23',
    isPublic: true,
    lastModified: '11-05-23',
    userId: 20,
  },
  {
    id: 7,
    templateId: 1,
    link: 'https://www.hloom.com/images/marketing-intern-cv-template-standout.svg',
    createdAt: '04-01-24',
    isPublic: false,
    lastModified: '24-06-23',
    userId: 21,
  },
  {
    id: 8,
    templateId: 1,
    link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SqnpfJKBVChreX2ALFJmj_PgIP5R12E4sA&s',
    createdAt: '04-08-23',
    isPublic: true,
    lastModified: '10-01-24',
    userId: 22,
  },
  {
    id: 9,
    templateId: 1,
    link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SqnpfJKBVChreX2ALFJmj_PgIP5R12E4sA&s',
    createdAt: '18-11-23',
    isPublic: true,
    lastModified: '15-06-23',
    userId: 23,
  },
  {
    id: 10,
    templateId: 1,
    link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SqnpfJKBVChreX2ALFJmj_PgIP5R12E4sA&s',
    createdAt: '08-11-23',
    isPublic: false,
    lastModified: '29-09-23',
    userId: 24,
  },
  {
    id: 11,
    templateId: 1,
    link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SqnpfJKBVChreX2ALFJmj_PgIP5R12E4sA&s',
    createdAt: '03-02-24',
    isPublic: false,
    lastModified: '02-10-23',
    userId: 25,
  },
  {
    id: 12,
    templateId: 1,
    link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SqnpfJKBVChreX2ALFJmj_PgIP5R12E4sA&s',
    createdAt: '15-05-23',
    isPublic: false,
    lastModified: '02-04-24',
    userId: 26,
  },
  {
    id: 13,
    templateId: 1,
    link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SqnpfJKBVChreX2ALFJmj_PgIP5R12E4sA&s',
    createdAt: '14-05-23',
    isPublic: true,
    lastModified: '15-08-23',
    userId: 27,
  },
  {
    id: 14,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '17-08-23',
    isPublic: false,
    lastModified: '08-03-24',
    userId: 28,
  },
  {
    id: 15,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '21-08-23',
    isPublic: true,
    lastModified: '11-07-23',
    userId: 29,
  },
  {
    id: 16,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '14-08-23',
    isPublic: true,
    lastModified: '18-08-23',
    userId: 30,
  },
  {
    id: 17,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '07-12-23',
    isPublic: false,
    lastModified: '27-05-23',
    userId: 31,
  },
  {
    id: 18,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '09-05-23',
    isPublic: false,
    lastModified: '02-06-23',
    userId: 32,
  },
  {
    id: 19,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '05-03-24',
    isPublic: false,
    lastModified: '26-07-23',
    userId: 33,
  },
  {
    id: 20,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '03-09-23',
    isPublic: true,
    lastModified: '05-03-24',
    userId: 34,
  },
  {
    id: 21,
    templateId: 1,
    link: 'https://d25zcttzf44i59.cloudfront.net/minimalist-resume-template.png',
    createdAt: '08-11-23',
    isPublic: true,
    lastModified: '27-05-23',
    userId: 35,
  },
  {
    id: 22,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '07-10-23',
    isPublic: true,
    lastModified: '05-06-23',
    userId: 36,
  },
  {
    id: 23,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '09-05-23',
    isPublic: false,
    lastModified: '30-01-24',
    userId: 37,
  },
  {
    id: 24,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '15-11-23',
    isPublic: true,
    lastModified: '06-01-24',
    userId: 38,
  },
  {
    id: 25,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '19-01-24',
    isPublic: true,
    lastModified: '04-04-24',
    userId: 39,
  },
  {
    id: 26,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '24-07-23',
    isPublic: true,
    lastModified: '02-07-23',
    userId: 40,
  },
  {
    id: 27,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '30-07-23',
    isPublic: true,
    lastModified: '14-09-23',
    userId: 41,
  },
  {
    id: 28,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '08-10-23',
    isPublic: true,
    lastModified: '14-01-24',
    userId: 42,
  },
  {
    id: 29,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '11-06-23',
    isPublic: false,
    lastModified: '22-08-23',
    userId: 43,
  },
  {
    id: 30,
    templateId: 1,
    link: 'https://www.cvmaker.uk/assets/examples/example-cv-supermarket-undefined.jpg',
    createdAt: '13-10-23',
    isPublic: true,
    lastModified: '21-09-23',
    userId: 44,
  },
];
