import { CreateJobDto } from '../dto/Req/create-job.dto';

export const jobs: CreateJobDto[] = [
  {
    id: 1,
    titleRecruitment: 'General Manager',
    majorId: 1,
    fieldsId: [10, 20, 5],
    campaignId: 1,
    currencyId: 1,
    salaryMin: 99,
    salaryMax: 2014,
    expId: 15,
    locationsId: [14],
    expiredDate: '2023-08-06',
    levelId: 5,
    status: true,
    companyId: 11,
    typeId: 1,
    quantity: 8,
    jobSchedule: 'Part time: Làm việc 2 ngày/tuần.',
    gender: 'Female',
    description:
      'Quản lý toàn bộ hoạt động của công ty, đảm bảo hoạt động hàng ngày diễn ra suôn sẻ và hiệu quả. Định hình chiến lược kinh doanh và phát triển tổ chức.\n',
    benefit:
      'Mức lương cao, bảo hiểm sức khỏe toàn diện, cơ hội thăng tiến trong sự nghiệp, kế hoạch nghỉ phép linh hoạt.',
    requirement:
      'Có ít nhất 5 năm kinh nghiệm quản lý trong lĩnh vực tương đương.',
    skills: 'Quản lý tổ chức, Chiến lược kinh doanh, Tối ưu hóa hoạt động',
  },
  {
    id: 2,
    titleRecruitment: 'Media Manager IV',
    majorId: 14,
    fieldsId: [2, 18, 33, 37],
    campaignId: 2,
    currencyId: 4,
    salaryMin: 97,
    salaryMax: 1616,
    expId: 10,
    locationsId: [3, 27],
    expiredDate: '2023-10-18',
    levelId: 9,
    status: true,
    companyId: 1,
    typeId: 1,
    quantity: 2,
    jobSchedule: 'Full time: Làm việc cả tuần, nghỉ Chủ Nhật.',
    gender: 'Any',
    description:
      'Quản lý chiến lược truyền thông và quảng cáo của công ty. Đảm bảo việc thực hiện các chiến dịch quảng cáo đúng hạn và hiệu quả.\n',
    benefit:
      'Môi trường làm việc sáng tạo, chế độ phúc lợi hấp dẫn, cơ hội tham gia các dự án sáng tạo, hỗ trợ đào tạo và phát triển cá nhân.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong lĩnh vực truyền thông, marketing hoặc quản lý.',
    skills: 'Chiến lược truyền thông, Quảng cáo, Sáng tạo',
  },
  {
    id: 3,
    titleRecruitment: 'Health Coach I',
    majorId: 21,
    fieldsId: [6, 8, 14, 30, 40],
    campaignId: 3,
    currencyId: 3,
    salaryMin: 79,
    salaryMax: 2700,
    expId: 4,
    locationsId: [35],
    expiredDate: '2024-06-29',
    levelId: 4,
    status: true,
    companyId: 1,
    typeId: 3,
    quantity: 3,
    jobSchedule: 'Internship: Làm việc 3 ngày/tuần.',
    gender: 'Male',
    description:
      'Hướng dẫn và tư vấn cho cá nhân hoặc nhóm về cách duy trì một lối sống lành mạnh và chăm sóc sức khỏe cá nhân.\n',
    benefit:
      'Được hỗ trợ học phí cho các khóa đào tạo chuyên ngành, cơ hội tham gia các sự kiện thể thao và sức khỏe, kế hoạch làm việc linh hoạt.',
    requirement:
      'Bằng cử nhân trong lĩnh vực liên quan đến sức khỏe, tư duy logic và khả năng giao tiếp tốt.',
    skills: 'Tư vấn sức khỏe, Tư duy logic, Giao tiếp hiệu quả',
  },
  {
    id: 4,
    titleRecruitment: 'Design Engineer',
    majorId: 5,
    fieldsId: [1, 4, 22],
    campaignId: 4,
    currencyId: 3,
    salaryMin: 50,
    salaryMax: 1435,
    expId: 14,
    locationsId: [19, 47],
    expiredDate: '2023-07-31',
    levelId: 4,
    status: true,
    companyId: 5,
    typeId: 1,
    quantity: 2,
    jobSchedule: 'Internship: Làm việc 4 ngày/tuần.',
    gender: 'Male',
    description:
      'Thiết kế và phát triển các sản phẩm, công nghệ hoặc hệ thống kỹ thuật. Đảm bảo rằng các sản phẩm đáp ứng được yêu cầu kỹ thuật và thiết kế.\n',
    benefit:
      'Tham gia vào quy trình phát triển sản phẩm từ ý tưởng đến sản phẩm cuối cùng, cơ hội học hỏi và phát triển kỹ năng kỹ thuật.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong ngành kỹ thuật, kinh nghiệm làm việc trên một dự án thiết kế kỹ thuật cần thiết.',
    skills: 'Thiết kế kỹ thuật, Kiểm tra sản phẩm, Lập trình máy tính',
  },
  {
    id: 5,
    titleRecruitment: 'Finance Analyst',
    majorId: 15,
    fieldsId: [7, 12, 25],
    campaignId: 5,
    currencyId: 1,
    salaryMin: 75,
    salaryMax: 2000,
    expId: 8,
    locationsId: [12, 33],
    expiredDate: '2024-11-15',
    levelId: 7,
    status: true,
    companyId: 3,
    typeId: 1,
    quantity: 4,
    jobSchedule: 'Full time: Làm việc 40 giờ/tuần.',
    gender: 'Any',
    description:
      'Phân tích dữ liệu tài chính, đưa ra dự báo và đề xuất chiến lược tài chính cho công ty. Đảm bảo tuân thủ các quy định về tài chính.\n',
    benefit:
      'Môi trường làm việc chuyên nghiệp, cơ hội thăng tiến, các khoản phúc lợi hấp dẫn.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong tài chính, kinh nghiệm làm việc trong phân tích tài chính.',
    skills: 'Phân tích tài chính, Dự báo tài chính, Quản lý dự án',
  },
  {
    id: 6,
    titleRecruitment: 'Senior Software Engineer',
    majorId: 3,
    fieldsId: [9, 13, 17, 21],
    campaignId: 6,
    currencyId: 2,
    salaryMin: 100,
    salaryMax: 2500,
    expId: 20,
    locationsId: [5, 8],
    expiredDate: '2024-12-05',
    levelId: 9,
    status: true,
    companyId: 6,
    typeId: 1,
    quantity: 6,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Phát triển và duy trì phần mềm, thực hiện các công việc phát triển, kiểm thử và triển khai phần mềm.\n',
    benefit:
      'Mức lương cạnh tranh, môi trường làm việc sáng tạo, cơ hội tham gia các dự án công nghệ mới.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong ngành công nghệ thông tin, kinh nghiệm làm việc trong phát triển phần mềm.',
    skills: 'Phát triển phần mềm, Kiểm thử phần mềm, Triển khai phần mềm',
  },
  {
    id: 7,
    titleRecruitment: 'Marketing Manager',
    majorId: 14,
    fieldsId: [2, 18, 24],
    campaignId: 7,
    currencyId: 4,
    salaryMin: 90,
    salaryMax: 1800,
    expId: 12,
    locationsId: [10, 22],
    expiredDate: '2023-10-12',
    levelId: 8,
    status: true,
    companyId: 7,
    typeId: 1,
    quantity: 4,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Phát triển chiến lược marketing và quảng cáo cho sản phẩm hoặc dịch vụ của công ty. Quản lý các chiến dịch tiếp thị.\n',
    benefit:
      'Mức lương cạnh tranh, cơ hội thăng tiến, môi trường làm việc năng động.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong marketing hoặc quản trị kinh doanh, kinh nghiệm làm việc trong quản lý marketing.',
    skills: 'Chiến lược marketing, Quảng cáo, Quản lý dự án',
  },
  {
    id: 8,
    titleRecruitment: 'UX/UI Designer',
    majorId: 5,
    fieldsId: [1, 4, 11],
    campaignId: 8,
    currencyId: 3,
    salaryMin: 65,
    salaryMax: 1550,
    expId: 6,
    locationsId: [2, 13],
    expiredDate: '2024-09-10',
    levelId: 6,
    status: true,
    companyId: 2,
    typeId: 1,
    quantity: 3,
    jobSchedule: 'Full time: Làm việc 40 giờ/tuần.',
    gender: 'Any',
    description:
      'Thiết kế và tối ưu hóa giao diện người dùng và trải nghiệm người dùng cho các sản phẩm số và ứng dụng.\n',
    benefit:
      'Mức lương hấp dẫn, cơ hội tham gia các dự án sáng tạo, hỗ trợ đào tạo và phát triển cá nhân.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong thiết kế đồ họa hoặc trải nghiệm người dùng, kinh nghiệm làm việc trong thiết kế giao diện người dùng.',
    skills:
      'Thiết kế giao diện người dùng, Trải nghiệm người dùng, Tối ưu hóa giao diện',
  },
  {
    id: 9,
    titleRecruitment: 'Content Writer',
    majorId: 13,
    fieldsId: [3, 15, 28],
    campaignId: 9,
    currencyId: 2,
    salaryMin: 45,
    salaryMax: 1300,
    expId: 3,
    locationsId: [9, 16],
    expiredDate: '2024-08-22',
    levelId: 5,
    status: true,
    companyId: 4,
    typeId: 1,
    quantity: 5,
    jobSchedule: 'Full time: Làm việc 40 giờ/tuần.',
    gender: 'Any',
    description:
      'Tạo ra nội dung chất lượng cho các trang web, blog, bài viết báo chí và các nội dung truyền thông khác của công ty.\n',
    benefit:
      'Mức lương hấp dẫn, cơ hội thăng tiến, môi trường làm việc sáng tạo.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong viết văn hoặc truyền thông, kinh nghiệm làm việc trong viết nội dung.',
    skills: 'Viết văn, Nội dung truyền thông, SEO',
  },
  {
    id: 10,
    titleRecruitment: 'Human Resources Coordinator',
    majorId: 11,
    fieldsId: [16, 23, 26],
    campaignId: 10,
    currencyId: 1,
    salaryMin: 60,
    salaryMax: 1600,
    expId: 6,
    locationsId: [1, 41],
    expiredDate: '2023-07-20',
    levelId: 5,
    status: true,
    companyId: 8,
    typeId: 1,
    quantity: 3,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Quản lý các hoạt động nhân sự, bao gồm tuyển dụng, huấn luyện, và quản lý hiệu suất. Đảm bảo tuân thủ quy trình nhân sự và luật lao động.\n',
    benefit:
      'Mức lương hấp dẫn, chế độ phúc lợi đầy đủ, cơ hội thăng tiến trong sự nghiệp.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong quản lý nhân sự hoặc các lĩnh vực liên quan, kinh nghiệm làm việc trong quản lý nhân sự.',
    skills: 'Quản lý nhân sự, Tuyển dụng, Huấn luyện',
  },
  {
    id: 11,
    titleRecruitment: 'Customer Support Specialist',
    majorId: 22,
    fieldsId: [19, 29, 34],
    campaignId: 11,
    currencyId: 4,
    salaryMin: 40,
    salaryMax: 1200,
    expId: 2,
    locationsId: [30, 44],
    expiredDate: '2024-09-28',
    levelId: 4,
    status: true,
    companyId: 9,
    typeId: 1,
    quantity: 5,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Hỗ trợ và giải quyết các vấn đề của khách hàng thông qua điện thoại, email hoặc trò chuyện trực tuyến. Cung cấp dịch vụ chăm sóc khách hàng chất lượng cao.\n',
    benefit:
      'Môi trường làm việc năng động, cơ hội thăng tiến, chế độ phúc lợi đầy đủ.',
    requirement:
      'Bằng cử nhân hoặc cao hơn, kỹ năng giao tiếp tốt và khả năng giải quyết vấn đề.',
    skills: 'Hỗ trợ khách hàng, Giao tiếp, Giải quyết vấn đề',
  },
  {
    id: 12,
    titleRecruitment: 'Data Scientist',
    majorId: 17,
    fieldsId: [5, 8, 32],
    campaignId: 12,
    currencyId: 3,
    salaryMin: 85,
    salaryMax: 2200,
    expId: 18,
    locationsId: [18, 36],
    expiredDate: '2023-10-08',
    levelId: 8,
    status: true,
    companyId: 10,
    typeId: 1,
    quantity: 3,
    jobSchedule: 'Full time: Làm việc 40 giờ/tuần.',
    gender: 'Any',
    description:
      'Phân tích dữ liệu và tạo ra các mô hình dự đoán và phân tích để hỗ trợ quyết định kinh doanh. Phát triển các giải pháp dựa trên dữ liệu.\n',
    benefit:
      'Mức lương cạnh tranh, cơ hội thăng tiến, môi trường làm việc năng động.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong khoa học dữ liệu hoặc các lĩnh vực liên quan, kinh nghiệm làm việc trong phân tích dữ liệu.',
    skills: 'Phân tích dữ liệu, Mô hình dự đoán, Lập trình Python',
  },
  {
    id: 13,
    titleRecruitment: 'Quality Assurance Engineer',
    majorId: 3,
    fieldsId: [9, 13, 17],
    campaignId: 13,
    currencyId: 1,
    salaryMin: 55,
    salaryMax: 1350,
    expId: 6,
    locationsId: [6, 25],
    expiredDate: '2024-12-17',
    levelId: 6,
    status: true,
    companyId: 11,
    typeId: 1,
    quantity: 4,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Kiểm tra và đảm bảo chất lượng của sản phẩm phần mềm. Xác định và báo cáo lỗi và vấn đề chất lượng.\n',
    benefit:
      'Mức lương cạnh tranh, cơ hội thăng tiến, môi trường làm việc năng động.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong ngành công nghệ thông tin, kinh nghiệm làm việc trong kiểm thử phần mềm.',
    skills: 'Kiểm thử phần mềm, Xác định lỗi, Báo cáo chất lượng',
  },
  {
    id: 14,
    titleRecruitment: 'Sales Representative',
    majorId: 20,
    fieldsId: [31, 35, 38],
    campaignId: 14,
    currencyId: 2,
    salaryMin: 45,
    salaryMax: 1500,
    expId: 2,
    locationsId: [7, 20],
    expiredDate: '2024-09-14',
    levelId: 4,
    status: true,
    companyId: 5,
    typeId: 1,
    quantity: 6,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Tìm kiếm khách hàng tiềm năng và xây dựng mối quan hệ với họ. Đề xuất và bán các sản phẩm hoặc dịch vụ của công ty.\n',
    benefit:
      'Mức lương cạnh tranh, chế độ phúc lợi đầy đủ, cơ hội thăng tiến trong sự nghiệp.',
    requirement:
      'Bằng cử nhân hoặc cao hơn, kỹ năng giao tiếp tốt và khả năng đàm phán.',
    skills: 'Bán hàng, Xây dựng mối quan hệ, Giao tiếp',
  },
  {
    id: 15,
    titleRecruitment: 'Graphic Designer',
    majorId: 5,
    fieldsId: [1, 4, 22],
    campaignId: 15,
    currencyId: 3,
    salaryMin: 60,
    salaryMax: 1400,
    expId: 4,
    locationsId: [4, 26],
    expiredDate: '2024-11-25',
    levelId: 5,
    status: true,
    companyId: 7,
    typeId: 1,
    quantity: 3,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Thiết kế đồ họa cho các sản phẩm in và kỹ thuật số. Tạo ra các ý tưởng sáng tạo và thiết kế đồ họa độc đáo.\n',
    benefit:
      'Mức lương hấp dẫn, cơ hội tham gia vào các dự án sáng tạo, môi trường làm việc năng động.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong thiết kế đồ họa hoặc lĩnh vực liên quan, kinh nghiệm làm việc trong thiết kế đồ họa.',
    skills: 'Thiết kế đồ họa, Sáng tạo, Ý tưởng độc đáo',
  },
  {
    id: 16,
    titleRecruitment: 'Project Manager',
    majorId: 12,
    fieldsId: [27, 36, 39],
    campaignId: 16,
    currencyId: 4,
    salaryMin: 80,
    salaryMax: 1900,
    expId: 11,
    locationsId: [11, 28],
    expiredDate: '2024-08-30',
    levelId: 7,
    status: true,
    companyId: 8,
    typeId: 1,
    quantity: 4,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Quản lý và điều phối các dự án từ khâu lập kế hoạch đến triển khai và đánh giá. Đảm bảo rằng các dự án hoàn thành đúng hạn và ngân sách.\n',
    benefit:
      'Mức lương cạnh tranh, cơ hội thăng tiến, môi trường làm việc năng động.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong quản lý dự án hoặc các lĩnh vực liên quan, kinh nghiệm làm việc trong quản lý dự án.',
    skills: 'Quản lý dự án, Lập kế hoạch, Đánh giá dự án',
  },
  {
    id: 17,
    titleRecruitment: 'Legal Counsel',
    majorId: 10,
    fieldsId: [15, 28, 30],
    campaignId: 17,
    currencyId: 1,
    salaryMin: 85,
    salaryMax: 2300,
    expId: 16,
    locationsId: [15, 37],
    expiredDate: '2024-11-09',
    levelId: 8,
    status: true,
    companyId: 3,
    typeId: 1,
    quantity: 3,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Cung cấp tư vấn pháp lý và đại diện pháp lý cho công ty trong các vấn đề pháp lý. Đảm bảo tuân thủ các quy định pháp lý.\n',
    benefit:
      'Mức lương cạnh tranh, cơ hội thăng tiến, môi trường làm việc chuyên nghiệp.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong lĩnh vực pháp lý hoặc luật sư được cấp phép, kinh nghiệm làm việc trong tư vấn pháp lý.',
    skills: 'Tư vấn pháp lý, Đại diện pháp lý, Tuân thủ quy định pháp lý',
  },
  {
    id: 18,
    titleRecruitment: 'Business Analyst',
    majorId: 15,
    fieldsId: [7, 12, 33],
    campaignId: 18,
    currencyId: 3,
    salaryMin: 70,
    salaryMax: 1800,
    expId: 8,
    locationsId: [23, 32],
    expiredDate: '2024-12-18',
    levelId: 6,
    status: true,
    companyId: 2,
    typeId: 1,
    quantity: 4,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Phân tích yêu cầu kinh doanh và tạo ra các giải pháp công nghệ phù hợp. Hỗ trợ quy trình phát triển và triển khai sản phẩm.\n',
    benefit:
      'Mức lương cạnh tranh, cơ hội thăng tiến, môi trường làm việc năng động.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong kinh doanh hoặc công nghệ thông tin, kinh nghiệm làm việc trong phân tích yêu cầu kinh doanh.',
    skills:
      'Phân tích yêu cầu, Giải pháp công nghệ, Hỗ trợ quy trình phát triển',
  },
  {
    id: 19,
    titleRecruitment: 'Social Media Coordinator',
    majorId: 14,
    fieldsId: [2, 18, 24],
    campaignId: 19,
    currencyId: 2,
    salaryMin: 50,
    salaryMax: 1350,
    expId: 5,
    locationsId: [21, 42],
    expiredDate: '2024-11-28',
    levelId: 4,
    status: true,
    companyId: 10,
    typeId: 1,
    quantity: 3,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Quản lý và cập nhật các kênh truyền thông xã hội của công ty. Tạo ra nội dung và quảng cáo hấp dẫn.\n',
    benefit:
      'Mức lương cạnh tranh, cơ hội thăng tiến, môi trường làm việc sáng tạo.',
    requirement:
      'Bằng cử nhân hoặc cao hơn trong marketing hoặc truyền thông, kinh nghiệm làm việc trong quản lý truyền thông xã hội.',
    skills: 'Quản lý truyền thông xã hội, Tạo nội dung, Quảng cáo truyền thông',
  },
  {
    id: 20,
    titleRecruitment: 'Customer Success Manager',
    majorId: 22,
    fieldsId: [19, 29, 34],
    campaignId: 20,
    currencyId: 4,
    salaryMin: 60,
    salaryMax: 1500,
    expId: 3,
    locationsId: [24, 45],
    expiredDate: '2024-12-07',
    levelId: 5,
    status: true,
    companyId: 8,
    typeId: 1,
    quantity: 4,
    jobSchedule: 'Full time: Làm việc từ thứ Hai đến thứ Sáu.',
    gender: 'Any',
    description:
      'Quản lý mối quan hệ với khách hàng và đảm bảo họ nhận được giá trị tối đa từ sản phẩm hoặc dịch vụ của công ty.\n',
    benefit:
      'Mức lương cạnh tranh, chế độ phúc lợi đầy đủ, cơ hội thăng tiến trong sự nghiệp.',
    requirement:
      'Bằng cử nhân hoặc cao hơn, kỹ năng giao tiếp tốt và khả năng làm việc với khách hàng.',
    skills:
      'Quản lý khách hàng, Tạo giá trị cho khách hàng, Giao tiếp hiệu quả',
  },
];
