import { CreateJobDto } from '../dto/Req/create-job.dto';

export const jobs: CreateJobDto[] = [
  {
    titleRecruitment: 'Software Engineer',
    majorId: 1,
    fieldsId: [2, 3],
    typeId: 1,
    currencyId: 1,
    levelId: 2,
    campaignId: 123,
    companyId: 1,
    salaryMin: 60000,
    salaryMax: 80000,
    expId: 3,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are looking for a skilled Software Engineer to join our team...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Computer Science or related field, 3+ years of experience...",
    skill: 'Java, Python, JavaScript, SQL',
  },
  {
    titleRecruitment: 'Web Developer',
    majorId: 1,
    fieldsId: [2, 3],
    typeId: 1,
    currencyId: 1,
    levelId: 2,
    campaignId: 123,
    companyId: 2,
    salaryMin: 55000,
    salaryMax: 75000,
    expId: 3,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are seeking a talented Web Developer to join our dynamic team...',
    benefit:
      'Competitive salary, flexible work hours, opportunity for growth...',
    requirement:
      "Bachelor's degree in Computer Science or related field, 2+ years of experience...",
    skill: 'HTML, CSS, JavaScript, React',
  },
  {
    titleRecruitment: 'Data Analyst',
    majorId: 2,
    fieldsId: [3, 4],
    typeId: 1,
    currencyId: 1,
    levelId: 3,
    campaignId: 123,
    companyId: 3,
    salaryMin: 60000,
    salaryMax: 80000,
    expId: 4,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are seeking a motivated Data Analyst to join our analytics team...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Statistics or related field, 2+ years of experience...",
    skill: 'SQL, Excel, Python, Data Visualization',
  },
  {
    titleRecruitment: 'Network Administrator',
    majorId: 3,
    fieldsId: [4, 5],
    typeId: 1,
    currencyId: 1,
    levelId: 4,
    campaignId: 123,
    companyId: 4,
    salaryMin: 65000,
    salaryMax: 85000,
    expId: 5,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are seeking an experienced Network Administrator to manage our network infrastructure...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Information Technology or related field, 4+ years of experience...",
    skill: 'Cisco, Juniper, TCP/IP, Network Security',
  },
  {
    titleRecruitment: 'UX Designer',
    majorId: 4,
    fieldsId: [5, 6],
    typeId: 1,
    currencyId: 1,
    levelId: 5,
    campaignId: 123,
    companyId: 5,
    salaryMin: 55000,
    salaryMax: 75000,
    expId: 3,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are looking for a talented UX Designer to create amazing user experiences...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Graphic Design or related field, 2+ years of experience...",
    skill: 'Adobe XD, Sketch, Wireframing, User Testing',
  },
  {
    titleRecruitment: 'Systems Engineer',
    majorId: 5,
    fieldsId: [6, 7],
    typeId: 1,
    currencyId: 1,
    levelId: 6,
    campaignId: 123,
    companyId: 6,
    salaryMin: 70000,
    salaryMax: 90000,
    expId: 4,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are seeking a highly skilled Systems Engineer to join our IT team...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Computer Science or related field, 4+ years of experience...",
    skill: 'Linux, Windows Server, VMware, Network Administration',
  },
  {
    titleRecruitment: 'Product Manager',
    majorId: 6,
    fieldsId: [7, 8],
    typeId: 1,
    currencyId: 1,
    levelId: 7,
    campaignId: 123,
    companyId: 7,
    salaryMin: 75000,
    salaryMax: 95000,
    expId: 5,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are seeking an experienced Product Manager to lead our product development efforts...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Business or related field, 5+ years of experience...",
    skill: 'Product Management, Agile, Scrum, Market Research',
  },
  {
    titleRecruitment: 'Software Developer',
    majorId: 7,
    fieldsId: [8, 9],
    typeId: 1,
    currencyId: 1,
    levelId: 8,
    campaignId: 123,
    companyId: 8,
    salaryMin: 60000,
    salaryMax: 80000,
    expId: 6,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are looking for a talented Software Developer to design and implement software solutions...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Computer Science or related field, 6+ years of experience...",
    skill: 'Java, C#, .NET, SQL',
  },
  {
    titleRecruitment: 'Mobile App Developer',
    majorId: 8,
    fieldsId: [9, 10],
    typeId: 1,
    currencyId: 1,
    levelId: 9,
    campaignId: 123,
    companyId: 9,
    salaryMin: 65000,
    salaryMax: 85000,
    expId: 7,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are seeking a skilled Mobile App Developer to create innovative mobile applications...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Computer Science or related field, 7+ years of experience...",
    skill: 'iOS, Android, Swift, Kotlin',
  },
  {
    titleRecruitment: 'Frontend Developer',
    majorId: 9,
    fieldsId: [10, 11],
    typeId: 1,
    currencyId: 1,
    levelId: 10,
    campaignId: 123,
    companyId: 10,
    salaryMin: 60000,
    salaryMax: 80000,
    expId: 8,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are looking for a talented Frontend Developer to create engaging user interfaces...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Computer Science or related field, 8+ years of experience...",
    skill: 'HTML, CSS, JavaScript, React',
  },
  {
    titleRecruitment: 'Backend Developer',
    majorId: 10,
    fieldsId: [11, 12],
    typeId: 1,
    currencyId: 1,
    levelId: 11,
    campaignId: 123,
    companyId: 11,
    salaryMin: 65000,
    salaryMax: 85000,
    expId: 9,
    locationsId: [4, 5],
    expiredDate: '2024-05-01',
    quantity: 1,
    jobSchedule: '8:00am-17:00pm T2-T6',
    gender: 'Any',
    description:
      'We are seeking a skilled Backend Developer to design and implement server-side logic...',
    benefit: 'Competitive salary, health benefits, flexible working hours...',
    requirement:
      "Bachelor's degree in Computer Science or related field, 9+ years of experience...",
    skill: 'Node.js, Python, Ruby, Java',
  },
];
