import { NotificationStatus } from '../../domain/aggregate';
import { NotificationSchema, UserNotificationSchema } from '../schema';

export const notifications: NotificationSchema[] = [
  {
    id: 1,
    title: 'Noti 1',
    content: 'Tìm việc làm an toàn cùng TopCV',
    createdAt: new Date('2023-09-09'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 2,
    title: 'Noti 2',
    content: 'Scheduled Maintenance Tomorrow from 11:00 PM to 3:00 AM.',
    createdAt: new Date('2023-09-05'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 3,
    title: 'Noti 3',
    content: 'Deadline for Project XYZ is [Insert Deadline Date].',
    createdAt: new Date('2023-11-15'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 4,
    title: 'Noti 4',
    content: 'Company Picnic Next Saturday at 12:00 PM.',
    createdAt: new Date('2024-02-05'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 5,
    title: 'Noti 5',
    content: 'Congratulations on Your [Insert Number] Year Work Anniversary!',
    createdAt: new Date('2024-03-26'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 6,
    title: 'Noti 6',
    content: 'Action Required on Pending Invoices.',
    createdAt: new Date('2023-07-06'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 7,
    title: 'Noti 7',
    content: 'Changes to Employee Benefits Policy - Please Review.',
    createdAt: new Date('2023-09-15'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 8,
    title: 'Noti 8',
    content: 'Lunch and Learn Session on [Topic] Next [Insert Date] at 12:00 PM.',
    createdAt: new Date('2024-01-31'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 9,
    title: 'Noti 9',
    content: "Happy Birthday [Recipient''s Name]! 🎉🎂",
    createdAt: new Date('2024-03-10'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 10,
    title: 'Noti 10',
    content: 'Quarterly Review Meeting Tomorrow at 2:00 PM.',
    createdAt: new Date('2023-11-25'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 11,
    title: 'Noti 11',
    content: 'Thank You for Your Feedback on [Project/Event/Service].',
    createdAt: new Date('2024-03-19'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 12,
    title: 'Noti 12',
    content: 'Webinar on [Topic] Next [Insert Date] at 3:00 PM - Register Now!',
    createdAt: new Date('2023-05-19'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 13,
    title: 'Noti 13',
    content: 'Performance Evaluation Deadline: [Insert Deadline Date].',
    createdAt: new Date('2024-01-28'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 14,
    title: 'Noti 14',
    content: "New Employee [New Employee''s Name] Joining Our Team on [Insert Start Date].",
    createdAt: new Date('2023-07-31'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 15,
    title: 'Noti 15',
    content: 'Updated Company Policy Handbook Attached - Please Review.',
    createdAt: new Date('2024-03-16'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 16,
    title: 'Noti 16',
    content: 'Networking Mixer Event Next Thursday - Save the Date!',
    createdAt: new Date('2023-06-05'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 17,
    title: 'Noti 17',
    content: 'Reminder: All Hands Meeting Today at 3:00 PM.',
    createdAt: new Date('2023-08-10'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 18,
    title: 'Noti 18',
    content: 'RSVP Reminder for [Event Name] by [Insert RSVP Deadline].',
    createdAt: new Date('2024-03-21'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 19,
    title: 'Noti 19',
    content: 'Emergency Drill Tomorrow at 9:00 AM - Please Participate.',
    createdAt: new Date('2023-07-06'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
  {
    id: 20,
    title: 'Noti 20',
    content: 'Happy Holidays! Office Closed on [Holiday Date].',
    createdAt: new Date('2023-06-25'),
    link: 'https://www.topcv.vn/faqs/find-a-safe-job',
  },
];


export const userNotifications: Omit<UserNotificationSchema, "notification">[] = [
  { userId: 'user-2', notificationId: 20, status: NotificationStatus.READ },
  { userId: 'user-17', notificationId: 19, status: NotificationStatus.READ },
  { userId: 'user-7', notificationId: 5, status: NotificationStatus.READ },
  { userId: 'user-17', notificationId: 16, status: NotificationStatus.UNREAD },
  { userId: 'user-14', notificationId: 2, status: NotificationStatus.UNREAD },
  { userId: 'user-1', notificationId: 6, status: NotificationStatus.UNREAD },
  { userId: 'user-16', notificationId: 18, status: NotificationStatus.READ },
  { userId: 'user-19', notificationId: 14, status: NotificationStatus.UNREAD },
  { userId: 'user-12', notificationId: 14, status: NotificationStatus.READ },
  { userId: 'user-1', notificationId: 19, status: NotificationStatus.READ },
  { userId: 'user-11', notificationId: 9, status: NotificationStatus.READ },
  { userId: 'user-18', notificationId: 12, status: NotificationStatus.READ },
  { userId: 'user-6', notificationId: 1, status: NotificationStatus.UNREAD },
  { userId: 'user-1', notificationId: 5, status: NotificationStatus.UNREAD },
  { userId: 'user-1', notificationId: 9, status: NotificationStatus.READ },
  { userId: 'user-1', notificationId: 3, status: NotificationStatus.UNREAD },
  { userId: 'user-15', notificationId: 20, status: NotificationStatus.READ },
  { userId: 'user-15', notificationId: 16, status: NotificationStatus.UNREAD },
  { userId: 'user-5', notificationId: 1, status: NotificationStatus.UNREAD },
  { userId: 'user-5', notificationId: 11, status: NotificationStatus.UNREAD },
  { userId: 'user-5', notificationId: 2, status: NotificationStatus.READ },
  { userId: 'user-14', notificationId: 18, status: NotificationStatus.UNREAD },
  { userId: 'user-8', notificationId: 5, status: NotificationStatus.UNREAD },
  { userId: 'user-3', notificationId: 5, status: NotificationStatus.UNREAD },
  { userId: 'user-1', notificationId: 14, status: NotificationStatus.READ },
  { userId: 'user-13', notificationId: 14, status: NotificationStatus.UNREAD },
  { userId: 'user-15', notificationId: 12, status: NotificationStatus.READ },
  { userId: 'user-18', notificationId: 4, status: NotificationStatus.READ },
  { userId: 'user-17', notificationId: 11, status: NotificationStatus.READ },
  { userId: 'user-6', notificationId: 5, status: NotificationStatus.READ },
  { userId: 'user-19', notificationId: 17, status: NotificationStatus.UNREAD },
  { userId: 'user-15', notificationId: 1, status: NotificationStatus.UNREAD },
  { userId: 'user-13', notificationId: 18, status: NotificationStatus.READ },
  { userId: 'user-11', notificationId: 2, status: NotificationStatus.UNREAD },
  { userId: 'user-9', notificationId: 4, status: NotificationStatus.READ },
  { userId: 'user-18', notificationId: 6, status: NotificationStatus.UNREAD },
  { userId: 'user-13', notificationId: 13, status: NotificationStatus.UNREAD },
  { userId: 'user-9', notificationId: 19, status: NotificationStatus.UNREAD },
  { userId: 'user-20', notificationId: 13, status: NotificationStatus.READ },
  { userId: 'user-15', notificationId: 9, status: NotificationStatus.UNREAD },
  { userId: 'user-6', notificationId: 2, status: NotificationStatus.UNREAD },
  { userId: 'user-16', notificationId: 2, status: NotificationStatus.UNREAD },
  { userId: 'user-19', notificationId: 1, status: NotificationStatus.READ },
  { userId: 'user-17', notificationId: 15, status: NotificationStatus.UNREAD },
  { userId: 'user-2', notificationId: 15, status: NotificationStatus.READ },
  { userId: 'user-13', notificationId: 8, status: NotificationStatus.READ },
  { userId: 'user-15', notificationId: 10, status: NotificationStatus.READ },
  { userId: 'user-1', notificationId: 11, status: NotificationStatus.READ },
];
