import { Application } from '../entities/application.entity';

export const applications: Application[] = [
  {
    id: 1,
    status: true,
    fullname: 'Emelyne Ivanuschka',
    phone: '682-849-4330',
    email: 'eivanuschka2t@paginegialle.it',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để ứng tuyển vào vị trí Media Manager IV. Kinh nghiệm và đam mê của tôi sẽ là một sự bổ sung đáng giá cho đội ngũ của công ty.\n\nTrân trọng,\nEmelyne Ivanuschka',
    createdAt: '2024-05-24',
    updateAt: '2023-06-27',
    campaignId: 2,
    userId: 15,
    cvId: 1,
  },
  {
    id: 2,
    status: true,
    fullname: 'Sarine Bayley',
    phone: '143-214-5112',
    email: 'sbayley2u@columbia.edu',
    coverLetter:
      'Kính gửi,\nTôi quan tâm đến vị trí Design Engineer và tin rằng kỹ năng của tôi sẽ đáp ứng yêu cầu công việc này. Xin vui lòng xem xét đơn ứng tuyển của tôi.\n\nTrân trọng,\nSarine Bayley',
    createdAt: '2024-05-25',
    updateAt: '2023-06-28',
    campaignId: 4,
    userId: 16,
    cvId: 2,
  },
  {
    id: 3,
    status: true,
    fullname: 'Kylen Muncer',
    phone: '916-812-1527',
    email: 'kmuncer2v@google.com.au',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để nộp đơn ứng tuyển vào vị trí Graphic Designer. Tôi tin rằng sự sáng tạo của tôi sẽ đem lại giá trị cho dự án của công ty.',
    createdAt: '2024-05-26',
    updateAt: '2023-06-29',
    campaignId: 7,
    userId: 17,
    cvId: 3,
  },
  {
    id: 4,
    status: true,
    fullname: 'Ham Feighry',
    phone: '402-678-3452',
    email: 'hfeighry2w@washingtonpost.com',
    coverLetter:
      'Kính gửi,\nTôi đang quan tâm đến vị trí Software Engineer I và hy vọng được làm việc cùng với đội ngũ của công ty. Xin vui lòng xem xét đơn ứng tuyển của tôi.',
    createdAt: '2024-05-27',
    updateAt: '2023-06-30',
    campaignId: 10,
    userId: 18,
    cvId: 4,
  },
  {
    id: 5,
    status: true,
    fullname: 'Amye Carvell',
    phone: '659-267-5956',
    email: 'acarvell2x@archive.org',
    coverLetter:
      'Kính gửi,\nTôi quan tâm đến vị trí Graphic Designer và tin rằng kỹ năng thiết kế của tôi sẽ đem lại sự sáng tạo cho công ty. Mong nhận được phản hồi từ bạn.\n\nTrân trọng,\nAmye Carvell',
    createdAt: '2024-05-28',
    updateAt: '2023-07-01',
    campaignId: 7,
    userId: 19,
    cvId: 5,
  },
  {
    id: 6,
    status: false,
    fullname: 'Filmer MacGill',
    phone: '424-362-1010',
    email: 'fmacgill2y@army.mil',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để ứng tuyển vào vị trí Design Engineer. Kinh nghiệm và sự am hiểu của tôi sẽ giúp đưa dự án của công ty đạt được thành công.\n\nTrân trọng,\nFilmer MacGill',
    createdAt: '2024-05-29',
    updateAt: '2023-07-02',
    campaignId: 4,
    userId: 20,
    cvId: 6,
  },
  {
    id: 7,
    status: false,
    fullname: 'Emmalynne Stonner',
    phone: '687-940-0123',
    email: 'estonner2z@dagondesign.com',
    coverLetter:
      'Kính gửi,\nTôi đang quan tâm đến vị trí Health Coach I và mong muốn được góp phần vào sứ mệnh của công ty trong việc cải thiện sức khỏe cộng đồng.\n\nTrân trọng,\nEmmalynne Stonner',
    createdAt: '2024-05-30',
    updateAt: '2023-07-03',
    campaignId: 3,
    userId: 21,
    cvId: 7,
  },
  {
    id: 8,
    status: false,
    fullname: 'Angy Wrates',
    phone: '386-131-1192',
    email: 'awrates30@shop-pro.jp',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để ứng tuyển vào vị trí General Manager. Kinh nghiệm và kỹ năng lãnh đạo của tôi sẽ giúp thúc đẩy sự phát triển của công ty.\n\nTrân trọng,\nAngy Wrates',
    createdAt: '2024-05-31',
    updateAt: '2023-07-04',
    campaignId: 1,
    userId: 22,
    cvId: 8,
  },
  {
    id: 9,
    status: true,
    fullname: 'Marcille Itchingham',
    phone: '901-908-1994',
    email: 'mitchingham31@delicious.com',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để nộp đơn ứng tuyển vào vị trí General Manager. Tôi tin rằng kinh nghiệm và tầm nhìn chiến lược của tôi sẽ đem lại lợi ích cho công ty.\n\nTrân trọng,\nMarcille Itchingham',
    createdAt: '2024-06-01',
    updateAt: '2023-07-05',
    campaignId: 1,
    userId: 23,
    cvId: 9,
  },
  {
    id: 10,
    status: true,
    fullname: 'Joachim Jacox',
    phone: '848-356-6084',
    email: 'jjacox32@scientificamerican.com',
    coverLetter:
      'Tôi quan tâm đến vị trí General Manager và mong muốn góp phần vào sự phát triển của công ty. Xin vui lòng xem xét đơn ứng tuyển của tôi.\n\nTrân trọng,\nJoachim Jacox',
    createdAt: '2024-06-02',
    updateAt: '2023-07-06',
    campaignId: 1,
    userId: 24,
    cvId: 10,
  },
  {
    id: 11,
    status: false,
    fullname: 'Ave Arndell',
    phone: '373-797-6734',
    email: 'aarndell33@ca.gov',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để ứng tuyển vào vị trí Research Associate. Kinh nghiệm và kỹ năng nghiên cứu của tôi sẽ đóng góp vào dự án của công ty.\n\nTrân trọng,\nAve Arndell',
    createdAt: '2024-06-03',
    updateAt: '2023-07-07',
    campaignId: 9,
    userId: 25,
    cvId: 11,
  },
  {
    id: 12,
    status: false,
    fullname: 'Janeta Denidge',
    phone: '390-368-0250',
    email: 'jdenidge34@reddit.com',
    coverLetter:
      'Tôi đang quan tâm đến vị trí General Manager và tin rằng kinh nghiệm của tôi sẽ mang lại giá trị cho công ty. Xin vui lòng xem xét đơn ứng tuyển của tôi.\n\nTrân trọng,\nJaneta Denidge',
    createdAt: '2024-06-04',
    updateAt: '2023-07-08',
    campaignId: 1,
    userId: 26,
    cvId: 12,
  },
  {
    id: 13,
    status: false,
    fullname: 'Donna Langcaster',
    phone: '783-511-8220',
    email: 'dlangcaster35@slashdot.org',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để ứng tuyển vào vị trí Design Engineer. Tôi tin rằng kinh nghiệm và kỹ năng của tôi sẽ đóng góp vào dự án của công ty.\n\nTrân trọng,\nDonna Langcaster',
    createdAt: '2024-06-05',
    updateAt: '2023-07-09',
    campaignId: 4,
    userId: 27,
    cvId: 13,
  },
  {
    id: 14,
    status: true,
    fullname: 'Danni Giacomuzzi',
    phone: '274-532-5101',
    email: 'dgiacomuzzi36@theguardian.com',
    coverLetter:
      'Kính gửi,\nTôi đang quan tâm đến vị trí Budget/Accounting Analyst IV và mong muốn góp phần vào sự phát triển tài chính của công ty. Xin vui lòng xem xét đơn ứng tuyển của tôi.\n\nTrân trọng,\nDanni Giacomuzzi',
    createdAt: '2024-06-06',
    updateAt: '2023-07-10',
    campaignId: 8,
    userId: 28,
    cvId: 14,
  },
  {
    id: 15,
    status: true,
    fullname: 'Luca Clissold',
    phone: '776-156-5044',
    email: 'lclissold37@state.tx.us',
    coverLetter:
      'Kính gửi,\nTôi quan tâm đến vị trí Media Manager IV và tin rằng kinh nghiệm của tôi sẽ mang lại giá trị cho dự án của công ty. Mong nhận được phản hồi từ bạn.\n\nTrân trọng,\nLuca Clissold',
    createdAt: '2024-06-07',
    updateAt: '2023-07-11',
    campaignId: 2,
    userId: 29,
    cvId: 15,
  },
  {
    id: 16,
    status: false,
    fullname: 'Ingram Gradly',
    phone: '678-995-9280',
    email: 'igradly38@abc.net.au',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để nộp đơn ứng tuyển vào vị trí Health Coach I. Kinh nghiệm và sự am hiểu về sức khỏe của tôi sẽ đem lại lợi ích cho nhân viên và công ty.\n\nTrân trọng,\nIngram Gradly',
    createdAt: '2024-06-08',
    updateAt: '2023-07-12',
    campaignId: 3,
    userId: 30,
    cvId: 16,
  },
  {
    id: 17,
    status: true,
    fullname: 'Willamina Agg',
    phone: '665-465-7317',
    email: 'wagg39@webs.com',
    coverLetter:
      'Kính gửi,\nTôi đang quan tâm đến vị trí Accounting Assistant I và tin rằng kỹ năng tài chính của tôi sẽ đáp ứng yêu cầu công việc. Xin vui lòng xem xét đơn ứng tuyển của tôi.\n\nTrân trọng,\nWillamina Agg',
    createdAt: '2024-06-09',
    updateAt: '2023-07-13',
    campaignId: 5,
    userId: 31,
    cvId: 17,
  },
  {
    id: 18,
    status: true,
    fullname: 'Horatio Elsom',
    phone: '288-109-4541',
    email: 'helsom3a@xrea.com',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để ứng tuyển vào vị trí General Manager. Tôi tin rằng kinh nghiệm lãnh đạo và kỹ năng quản lý của tôi sẽ đem lại thành công cho công ty.\n\nTrân trọng,\nHoratio Elsom',
    createdAt: '2024-06-10',
    updateAt: '2023-07-14',
    campaignId: 1,
    userId: 32,
    cvId: 18,
  },
  {
    id: 19,
    status: true,
    fullname: 'Lyndy Dene',
    phone: '377-339-2969',
    email: 'ldene3b@topsy.com',
    coverLetter:
      'Tôi quan tâm đến vị trí Health Coach I và hy vọng được góp phần vào sứ mệnh của công ty trong việc cải thiện sức khỏe cộng đồng. Xin vui lòng xem xét đơn ứng tuyển của tôi.\n\nTrân trọng,\nLyndy Dene',
    createdAt: '2024-06-11',
    updateAt: '2023-07-15',
    campaignId: 3,
    userId: 33,
    cvId: 19,
  },
  {
    id: 20,
    status: false,
    fullname: 'Waylin MacVaugh',
    phone: '584-577-2404',
    email: 'wmacvaugh3c@yellowpages.com',
    coverLetter:
      'Kính gửi,\nTôi viết thư này để nộp đơn ứng tuyển vào vị trí General Manager. Kinh nghiệm và kỹ năng lãnh đạo của tôi sẽ là một nguồn lực quý giá cho sự phát triển của công ty.\n\nTrân trọng,\nWaylin MacVaugh',
    createdAt: '2024-06-12',
    updateAt: '2023-07-16',
    campaignId: 1,
    userId: 34,
    cvId: 20,
  },
];
